-- MySQL Script generated by MySQL Workbench
-- jeu. 07 févr. 2019 15:18:40 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Shop_base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Shop_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shop_base` DEFAULT CHARACTER SET utf8 ;
USE `Shop_base` ;

-- -----------------------------------------------------
-- Table `Shop_base`.`Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop_base`.`Produits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prix` DOUBLE NULL,
  `description` VARCHAR(150) NULL,
  `marque` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
